### PR TITLE
Puppeteer tests on skymap page along with typo fixes

### PR DESCRIPTION
**Pull request by JGong7**
Wrote puppeteer tests for every single constellation, along with the dragging feature.
Also, corrected the typo in skymap.js.

### CODE REVIEW

**Comment by ShashankVenkatramani** [comment]
Hey! It appears you added the package.json, and package_lock.json which should not be added for our client end as we don't use any frameworks at production time.

**Review by ShashankVenkatramani — CHANGES_REQUESTED** [review]
Remove package-lock and package.json

**Comment by JGong7** [comment]
package-lock and package.json have now been removed

**Comment by ShashankVenkatramani** [comment]
Canis Major is still missing a space, can you talk with Aiden regarding the display issues to figure out the optimal way to solve this without disturbing the rest of the code base by too much, and if there are disturbances let people know in slack

**Review by ShashankVenkatramani — APPROVED** [review]
Looks good!

**Pull request merged**
