### PR TITLE
Assets branch

### LINKED ISSUE #28: Update constellation names and constellations star locations
**Give a detailed description on the tasks and lay out each expectation for that task in a clear and concise manner**

The starmap is currently working with an older layout of the constellations and stars. Andy has created a new layout with additional images on the [assets branch](https://github.com/cse110-sp23-group16/cse110-sp23-group16/tree/assetsBranch). Remove old star locations in the js file, and update the new ones using an external JSON file as a source.

- [x] Update image path
- [x] Update star location
- [x] JSON File

**ETA: give a rough time estimate to complete this issue**

25 minutes.

**Additional Information?**

### LINKED ISSUE #29: Create the constellation drawings
Give a detailed description on the tasks and lay out each expectation for that task in a clear and concise manner

Create drawings for constellations that overlay onto the skymap

ETA: give a rough time estimate to complete this issue

2-3 hours

Additional Information?

Sub task for issue https://github.com/cse110-sp23-group16/cse110-sp23-group16/issues/3

### PR DESCRIPTION
**Pull request by A4Fang**
Updated the locations of the stars, added constellation drawings which are aligned with the stars themselves. Organized the asset directory

### CODE REVIEW

**Review by ShashankVenkatramani — CHANGES_REQUESTED** [review]
Constellations look great! One minor issue, with the changing of the file names and constellation locations we need to reinput them in the code now for the starmap (probably a hint that we should eventually make JSON type storage file to automatically parse it but we save that for later). I think we should make a second issue for changing the code and add it to this PR for now, and merge it once both are completed so that our deployment stays intact.

**Comment by ShashankVenkatramani** [comment]
Closes #28 Closes #29

**Comment by sorata000x** [comment]
Completed requested issue #28, please review.

**Review by ShashankVenkatramani — APPROVED** [review]
Looks Good!

**Pull request merged**
