### PR TITLE
Comments for explanation thank

### PR DESCRIPTION
**Pull request by VictorKuu**
please check to see if i did this right....there r no parameters/return values....which feels off with my comments.

### CODE REVIEW

**Comment by khushijpatel** [comment]
You could potentially use the @property for functions like the example in image? I don't think there's anything else that can be done for these 
image

Link to page: https://medium.com/@martink_rsa/js-docs-a-quickstart-guide-da6ce5df4a73

**Review by khushijpatel — CHANGES_REQUESTED** [review]
You could potentially use the @property for functions like the example in image? I don't think there's anything else that can be done for these 
image

Link to page: https://medium.com/@martink_rsa/js-docs-a-quickstart-guide-da6ce5df4a73

**Comment by VictorKuu** [comment]
is that just at the top of the document? the @property?

**Comment by khushijpatel** [comment]
Option 1) Do that for all functions at the top of the page
Option 2) Just add ` @property {Function} ` in front of the descriptions above each function

**Comment by khushijpatel** [comment]
Also, we should not be removing the team intro video (it was part of an assignment: https://canvas.ucsd.edu/courses/44983/assignments/617857)

**Review by khushijpatel — APPROVED** [review]
Looks great!

**Pull request merged**
