### PR TITLE
Filled in some actual response content

### LINKED ISSUE #37: Fill in actual responses for the response page
**Give a detailed description on the tasks and lay out each expectation for that task in a clear and concise manner**
The response page needs to have actual responses which all begin with a short and direct answer to the question (assuming questions all have to be closed-ended) and then expand on that through interpretation of the chosen constellation.

- [ ] list of short answers
- [ ] list of interpretation paragraphs
- [ ] randomized combination of the answer as well as the interpretation that's matching the given constellation

**ETA: give a rough time estimate to complete this issue**
one day

**Additional Information?**

### PR DESCRIPTION
**Pull request by Chengqianc**

### CODE REVIEW

**Comment by sorata000x** [comment]
Looking great so far! Don't forget to comment on the functions and codes so other team members can know what they do as well.

**Comment by Chengqianc** [comment]
Added comments for response.js

**Review by sorata000x — APPROVED** [review]
Looks good!

**Review by ChiSWong — APPROVED** [review]
good for now, make changes according to meeting note for May 21

**Pull request merged**
