### PR TITLE
4 New Constellations added

### PR DESCRIPTION
**Pull request by A4Fang**
The custom constellation is the armadillo dragon which is a tentative name unless if we want to stick with it while the other 3 constellations: Ursa Major (previously added with #54) , Carnia, and Ophiuchus are references to known ones

### CODE REVIEW

**Comment by khushijpatel** [comment]
Looks good to me, just run prettier to fix the merge issues
You first install prettier from npm (you can install it globally instead of in the repository only) with:
'npm install prettier@2.8.8 -g'

from there to run prettier you do
prettier --write dir
where it will recursively format files in the dir
so you can do
prettier --write .
at root of repo to format the whole thing

**Review by khushijpatel — CHANGES_REQUESTED** [review]
Looks good to me, just run prettier to fix the merge issues
You first install prettier from npm (you can install it globally instead of in the repository only) with:
'npm install prettier@2.8.8 -g'

from there to run prettier you do
prettier --write dir
where it will recursively format files in the dir
so you can do
prettier --write .
at root of repo to format the whole thing

**Comment by A4Fang** [comment]
It should be good now

**Review by ChiSWong — APPROVED** [review]
Beauty!

**Pull request merged**
