### PR TITLE
add skeleton of thank you page

### LINKED ISSUE #2: Create a thank you for visiting page
**Give a detailed description on the tasks and lay out each expectation for that task in a clear and concise manner**
Create a skeleton of the thank you for visiting page. Skeleton means have the HTML portion of the page done with the following:

1. Large text saying Thank you in the center of the page. 
2. A link back to the main landing page by saying something along lines of "Feel free to go back to the main page to try choose another constellation reading. Thanks for visiting, hope to see you again!"

**ETA: give a rough time estimate to complete this issue**
3 hours

**Additional Information?**
Make sure to push to the thank you page branch

### PR DESCRIPTION
**Pull request by khushijpatel**
Check issues page for this to see the thank you page skeleton. Image included in comments.

### CODE REVIEW

**Review by ChiSWong — APPROVED** [review]
looks good to me! should have no problem to merge 
just some very minor thing:
- while I do think it would be an issue, but are we allowed to use external css?
- don't think you need to spcific type="button" in the button tag

**Review by ShashankVenkatramani — CHANGES_REQUESTED** [review]
I agree with Chi, for the skeleton pages we should avoid importing libraries.

**Comment by khushijpatel** [comment]
Sounds good, getting rid of it, it was more so a setup for later future use but can be avoided when actually doing the css

**Comment by ChiSWong** [comment]
I see, then its all good!

**Review by ShashankVenkatramani — APPROVED** [review]
Looks good!

**Pull request merged**
