### PR TITLE
Fortune teller asset

### LINKED ISSUE #67: Design Fortune Teller Assets
**Give a detailed description on the tasks and lay out each expectation for that task in a clear and concise manner**
Create separate (or one) fortune teller designs for the following pages:

- [x] Landing page
- [x] Thank you page

**ETA: give a rough time estimate to complete this issue**
2-3 days

**Additional Information?**
Additional minor task: update the preview image and PSD file

### PR DESCRIPTION
**Pull request by A4Fang**
Added a fortune teller asset for the landing page and thank you page. I also updated the preview image and the PSD file from the last time I edited

### CODE REVIEW

**Review by ShashankVenkatramani — CHANGES_REQUESTED** [review]
Do you think you can modify the code so that the landing page and thank you page use these assets?

**Comment by A4Fang** [comment]
Aiden is working on the landing page, I can work on the thank you page but the landing page will need some changes in the files that I put here #100. I can remove the assets for the landing page for now and work on modifying the code for the thank you page

**Review by ShashankVenkatramani — DISMISSED** [review]
Looks good!

**Review by ShashankVenkatramani — APPROVED** [review]
Looks good!

**Pull request merged**
