### PR TITLE
Fix the constellation name for star connections

### PR DESCRIPTION
**Pull request by JGong7**
Added a space between Ursa Major and Armadillo Dragon. Originally for these two constellations, only the image showed but the dots are not connecting. After the fix, now they connect.

### CODE REVIEW

**Comment by ChiSWong** [comment]
Hey Jerry I found that there are some more naming conflicts that may raise issue, I chagned them up in my branch, the current bug should be fixed once my branch is merged

**Comment by JGong7** [comment]
Hi Chi. Since the asset is re-organized yesterday, and the typos were addressed in either previous PRs or my current PR that hasn't been closed yet, I would suggest merging this PR first, and then repull from main branch and see if the assets paths were correct.

**Review by sorata000x — APPROVED** [review]
LGTM

**Comment by ChiSWong** [comment]
sure you can push it first!

**Pull request merged**
