### PR TITLE
Fix UI screen size

### PR DESCRIPTION
**Pull request by sorata000x**
Tried and fix the ui of every page on different screen size and fixed any ui glitch I've found.

### CODE REVIEW

**Comment by sorata000x** [comment]
Closes #136

**Comment by ShashankVenkatramani** [comment]
Looks good! Single prettier issue stemming from main, we can hot fix that after merging in.

**Review by ShashankVenkatramani — DISMISSED** [review]
Looks good!

**Review by ShashankVenkatramani — DISMISSED** [review]
Looks good!

**Review by ShashankVenkatramani — APPROVED** [review]
Looks good!

**Pull request merged**
